name: Deploy-Orders

on:
  push:
    branches:
      - master
    paths:
      - 'server/orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Building Client
        run: |
          docker build -t shreyasssk/ticketing-orders:latest ./server/orders/
          docker build --cache-from shreyasssk/ticketing-orders:latest -t shreyasssk/ticketing-orders:$GITHUB_SHA ./server/orders/

      - name: Deploying to Docker Registry
        run: |
          docker push shreyasssk/ticketing-orders:$GITHUB_SHA
          docker push shreyasssk/ticketing-orders:latest
