name: Deploy-Tickets

on:
  push:
    branches:
      - master
    paths:
      - 'server/tickets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Building Client
        run: |
          docker build -t shreyasssk/ticketing-tickets:latest ./server/tickets/
          docker build --cache-from shreyasssk/ticketing-tickets:latest -t shreyasssk/ticketing-tickets:$GITHUB_SHA ./server/tickets/

      - name: Deploying to Docker Registry
        run: |
          docker push shreyasssk/ticketing-tickets:$GITHUB_SHA
          docker push shreyasssk/ticketing-tickets:latest
