name: Deploy-Payment

on:
  push:
    branches:
      - master
    paths:
      - 'server/payments/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Building Payments Service
        run: |
          docker build -t shreyasssk/ticketing-payments:latest ./server/payments/
          docker build --cache-from shreyasssk/ticketing-payments:latest -t shreyasssk/ticketing-payments:$GITHUB_SHA ./server/payments/

      - name: Deploying to Docker Registry
        run: |
          docker push shreyasssk/ticketing-payments:$GITHUB_SHA
          docker push shreyasssk/ticketing-payments:latest
