name: Deploy-Expiration

on:
  push:
    branches:
      - master
    paths:
      - 'server/expiration/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Building Expiration Service
        run: |
          docker build -t shreyasssk/ticketing-expiration:latest ./server/expiration/
          docker build --cache-from shreyasssk/ticketing-expiration:latest -t shreyasssk/ticketing-expiration:$GITHUB_SHA ./server/expiration/

      - name: Deploying to Docker Registry
        run: |
          docker push shreyasssk/ticketing-expiration:$GITHUB_SHA
          docker push shreyasssk/ticketing-expiration:latest
