name: Deploy-Client

on:
  push:
    branches:
      - master
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Building Tickets Service
        run: |
          docker build -t shreyasssk/ticketing-client:latest ./client/
          docker build --cache-from shreyasssk/ticketing-client:latest -t shreyasssk/ticketing-client:$GITHUB_SHA ./client/

      - name: Deploying to Docker Registry
        run: |
          docker push shreyasssk/ticketing-client:$GITHUB_SHA
          docker push shreyasssk/ticketing-client:latest
