name: Deploy-Auth

on:
  push:
    branches:
      - master
    paths:
      - 'server/auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Building Auth Service
        run: |
          docker build -t shreyasssk/ticketing-auth:latest ./server/auth/
          docker build --cache-from shreyasssk/ticketing-auth:latest -t shreyasssk/ticketing-auth:$GITHUB_SHA ./server/auth/

      - name: Deploying to Docker Registry
        run: |
          docker push shreyasssk/ticketing-auth:$GITHUB_SHA
          docker push shreyasssk/ticketing-auth:latest
